### ISSUE TITLE
Move link to Bootstrap lesson

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/html-css-sass#15]
The link for 'Improve Your Markup by Extending Classes' is all about Bootstrap, which developers haven't learned yet. I think we should consider moving it to https://github.com/ga-wdi-boston/html-css-layout-bootstrap-sass.

**Comment by BenGitsCode** [comment]
Addressed in 954fe8fa.

Needs to be addressed in ga-wdi-boston/html-css-layout-bootstrap-sass/issues/21

**Comment by MicFin** [comment]
Issue was addressed in this repository
commit: https://github.com/ga-wdi-boston/html-css-sass/commit/954fe8facd3228ef2e79e41f04d7169371f12a9a.

Issue was addressed in related repository 
issue:  https://github.com/ga-wdi-boston/html-css-layout-bootstrap-sass/issues/21
commit: https://github.com/ga-wdi-boston/html-css-layout-bootstrap-sass/commit/6f19daeead1516df0c6537df9aafae392bcd66a5.

This can be closed @raq929.

**Comment by jrhorn424** [comment]
As many eyes agree, I'm closing this.
