### ISSUE TITLE
Improper wording under "Move Quote Styles"

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/html-css-sass#7]
Exercise: Move Quote Styles

Move the quote style declarations into the theme. Why would we want to keep these styles in the theme module?

module should be It's own Theme

**Comment by J-Weeks** [comment]
Leaving this at the digression of the next instructor and closing.  @berziiii your call.

**Comment by gaand** [comment]
Please do not close things that are supposed to be reviewed (which is how I interpret "Leaving this at the digression of the next instructor").

**Comment by raq929** [comment]
Woo! I'm the next instructor. I think it's appropriate to have your quote styles included in your theme.

**Comment by MicFin** [comment]
I agree with @raq929 which I believe means we can leave it as is and close the issue for `lm01`.  @gaand who should close since it will not be addressed in a commit and the creator is not active.

**Comment by jrhorn424** [comment]
I'm closing this. Welcoming 🔨 in the event that's a mistake.
