### ISSUE TITLE
Rename '_breakpoint.scss' - remove underscore

### ISSUE THREAD

**Issue by MattB-GA-Boston** [ga-wdi-boston/html-css-sass#8]

**Comment by jrhorn424** [comment]
Thanks! I think I'll go with "tiny.scss" in the future.

**Comment by laurenfazah** [comment]
I fixed with removing the underscore, but didn't make the switch to tiny.scss

**Comment by jrhorn424** [comment]
The confusion was in having a mixin with a similar name to the file containing breakpoint declarations.

**Comment by laurenfazah** [comment]
Ah, I get it. I was planning to not have a "breakpoints.scss" and rather keep those media queries with their modules. In other words, emphasize the importance of breaking their CSS into separate, thoughtful modules, and keep the media queries for each in the bottom of each modules' file. Do you have anything against doing it that way? @jrhorn424

**Comment by jrhorn424** [comment]
No objections. 😄

**Comment by berziiii** [comment]
Seems to be corrected in solution branch. Can we close @jrhorn424?

**Comment by gaand** [comment]
@berziiii if Lauren's suggestions are incorporated, then please close.

**Comment by berziiii** [comment]
Closing. Reopen if needed
